# Generated by Django 3.0.2 on 2020-01-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sub',
        ),
    ]
