# Generated by Django 3.0.2 on 2020-01-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200116_0538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toping',
            new_name='Topping',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topings',
            new_name='toppings',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topings_count',
            new_name='toppings_count',
        ),
    ]
