# Generated by Django 3.0.2 on 2020-01-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200116_0624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Pizza_order',
        ),
    ]
