# Generated by Django 3.0.2 on 2020-01-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200117_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizza_toppings', to='orders.Topping'),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=8)),
                ('price_small', models.FloatField()),
                ('price_large', models.FloatField()),
                ('toppings_option', models.ManyToManyField(blank=True, related_name='pizza_options', to='orders.Topping_option')),
            ],
        ),
    ]
