# Generated by Django 3.0.2 on 2020-01-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200117_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=16)),
                ('toppings_option', models.CharField(default='Cheese', max_length=16)),
                ('price_small', models.FloatField()),
                ('price_large', models.FloatField()),
            ],
        ),
    ]
