# Generated by Django 3.0.2 on 2020-01-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200120_0510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza_order',
        ),
    ]
