# Generated by Django 3.0.2 on 2020-01-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_delete_pizza_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings_option',
            field=models.SmallIntegerField(default=0),
        ),
    ]
