# Generated by Django 3.0.2 on 2020-01-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pizza_type',
            field=models.CharField(blank=True, default='None', max_length=16),
        ),
    ]
