# Generated by Django 3.0.2 on 2020-02-04 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200130_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(default=datetime.datetime.now, verbose_name='date placed')),
                ('customer', models.CharField(max_length=64)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(default='Placed', max_length=16)),
                ('items', models.ManyToManyField(related_name='order', to='orders.OrderItem')),
            ],
        ),
    ]
