# Generated by Django 3.0.2 on 2020-02-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_onlineorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(default='Not Placed', max_length=16),
        ),
    ]
