# Generated by Django 3.0.2 on 2020-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200204_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='orders.OrderItem'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(default='Unplaced', max_length=16),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
