# Generated by Django 3.0.2 on 2020-02-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200204_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(default='unplaced', max_length=16),
        ),
    ]
