# Generated by Django 3.0.2 on 2020-02-17 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200215_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='placed',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 19, 35, 21, 224360), verbose_name='date placed'),
        ),
    ]
