# Generated by Django 3.0.2 on 2020-02-20 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200217_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='placed',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 22, 12, 5, 695526), verbose_name='date placed'),
        ),
    ]
