# Generated by Django 3.0.2 on 2020-02-20 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200220_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='html_id',
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='placed',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 22, 18, 48, 219206), verbose_name='date placed'),
        ),
    ]
