# Generated by Django 3.0.2 on 2020-02-22 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200220_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='html_id',
            field=models.CharField(default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='placed',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 22, 44, 41, 51692), verbose_name='date placed'),
        ),
    ]
